### PR TITLE
Deprecate `plone.app.widgets`

### LINKED ISSUE #19: p.a.widgets dependency?
According to @jensens https://github.com/plone/plone.app.widgets/issues/98#issuecomment-88097762 p.a.widgets got merged into here on commit https://github.com/plone/plone.app.z3cform/commit/6eb2ebd4b7f9232e95ad96455d4483d4b3c06eab

Still p.a.z3cform master depends on p.a.widgets on, setup.py, metadata.xml, top-level configure.zcml and also a test (plone/app/z3cform/tests/test_widgets.py) and on widgets.py.

So does p.a.widgets need to be used on plone 5 or should this package be fixed?

### PR DESCRIPTION
**Pull request by petschki**
Start reimplementing pieces of `plone.app.widgets` in the right place here.

Also split up huge module `plone.app.z3cform.widget` into smaller modules and placed import deprecation warnings.

Closes #19

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

lets see what breaks 😉

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Review by jensens — APPROVED** [review]

**Comment by fredvd** [comment]
@jenkins-plone-org please run jobs

**Comment by thet** [comment]
8)

**Pull request merged**
