### PR TITLE
Use interpolation

### PR DESCRIPTION
**Pull request by gforcada**
@petschki @plone/classicui-team should we use/prefer [Chameleon's interpolations](https://chameleon.readthedocs.io/en/latest/reference.html#operator) in templates to reduce the line count while making them more readable? 🤔 

I'm a huge fan of them ✨

### CODE REVIEW

**Comment by thet** [comment]
+1 for this change.

But IMO we should also think on how to get rid of the absolutely incomplete listing of possible HTML attributes (onmouseclick, etc) and keep a way on inserting arbitrary attributes via a different mechanism.

**Comment by mauritsvanrees** [comment]
I prefer Chameleon syntax as well.

**Comment by petschki** [comment]
@thet I also thought about a more generic approach to render those attributes. There's a definition of HTML elements and their valid attributes here https://www.w3.org/TR/xhtml1/dtds.html#dtdentry_xhtml1-strict.dtd_coreattrs - but I do not know a python package which returns a mapping of those definitions. All in all it would also be the best to implement this in the `z3c.form.browser` widgets first and then adjust our `plone.app.z3cform` templates accordingly ...

**Comment by gforcada** [comment]
For the attributes one can do:

```python
def get_data(self):
    return {
        "onmouseclick": "javascript:alert('hi')",
        "title": "Something",
        "style": "background-color: red",
    }
```

And on the template:

```html
<a tal:attributes="view/get_data">hi!</a>
```

Then, as @petschki suggests, if we have a generic list of attributes that are tailored later on a per widget basis we can simplify it all 🎉 

On top of that, if the dictionary has an empty entry:

```python
def get_data(self):
    return {
        "onmouseclick": "javascript:alert('hi')",
        "title": "Something",
        "style": "",
    }
```

Chameleon already ignore the `style` attribute and does not add it.

So maybe the tailoring is not needed, as long as the default values are empty strings.

_Note:_ I haven't checked that detail exactly myself, but it is said on the documentation 😄

**Comment by petschki** [comment]
For the widget template such an attribute mapping and chameleon implementation would make sense.

But as @thet said it would definitely make sense to first think about how to sanitize the attributes defined here https://github.com/zopefoundation/z3c.form/blob/master/src/z3c/form/browser/interfaces.py and come up with a solution where we can hook into "html attribute values". Because now we copy almost all widget templates from z3c.form, wrap them to `IPloneFormLayer` and add bootstrap classes there ...  it would be more "z3cformish" to implement some kind of `HTMLElementAttributeAdapter` where you can override the defailt attribute values or add/remove custom attributes ... but that's definitely a z3c.form issue ...

**Comment by petschki** [comment]
> But as @thet said it would definitely make sense to first think about how to sanitize the attributes defined here https://github.com/zopefoundation/z3c.form/blob/master/src/z3c/form/browser/interfaces.py and come up with a solution where we can hook into "html attribute values". Because now we copy almost all widget templates from z3c.form, wrap them to `IPloneFormLayer` and add bootstrap classes there ... it would be more "z3cformish" to implement some kind of `HTMLElementAttributeAdapter` where you can override the default attribute values or add/remove custom attributes ... but that's definitely a z3c.form issue ...

Or maybe I'm missing something and it is already there somewhere?

/cc @dataflake @icemac

**Comment by icemac** [comment]
I don't know.

**Comment by thet** [comment]
I like @gforcada's approach. How we could get there is maybe something for the sprint next week...

**Comment by thet** [comment]
@gforcada I started working on an `attributes` property on widget views, just as outlined above.

These are the work-in-progress branches:
https://github.com/zopefoundation/z3c.form/tree/flexible-attributes
https://github.com/plone/plone.app.z3cform/tree/interpolated-attributes
https://github.com/plone/plone.app.registry/tree/dialog-instead-modal

**Comment by petschki** [comment]
This looks really promising. Maybe we get that far, that we do not have to override templates here anymore instead only define our attributes in the widget views. That'd be very nice!

**Comment by thet** [comment]
This is now the z3c.form PR:
https://github.com/zopefoundation/z3c.form/pull/116

**Comment by petschki** [comment]
So since we're using Chameleon templates in plone we can use the attribute expansion here when this PR is merged and released, right?

**Comment by thet** [comment]
Merged, but not yet released: https://github.com/zopefoundation/z3c.form/pull/116

**Comment by icemac** [comment]
> Merged, but not yet released: [zopefoundation/z3c.form#116](https://github.com/zopefoundation/z3c.form/pull/116)

Released in https://pypi.org/project/z3c.form/5.1/

**Comment by petschki** [comment]
I'll close this in favor of #181

**Pull request closed without merging**
