### PR TITLE
Fix LinkWidget selected tab on edit

### PR DESCRIPTION
**Pull request by mamico**
see #108 

it needs https://github.com/plone/mockup/pull/922

### CODE REVIEW

**Comment by mamico** [comment]
@jenkins-plone-org please run jobs

**Comment by mamico** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@mamico Doesn't it need an update of the bundles in `plone.staticresources` as well to work? But I think this is save to merge anyway.

**Comment by mamico** [comment]
> @mamico Doesn't it need an update of the bundles in `plone.staticresources` as well to work? But I think this is save to merge anyway.

@jensens Thanks! So `mockup` updating is not enough... Do we need to do a PR with compiled js/css also in plone.staticresources? No problem I will do ASAP.... but could this not be a job for a CI bot like Jenkins? Isn't it better / safer?

**Comment by jensens** [comment]
@mamico well, at the moment this is a manual task. yes, please do a PR there.

**Pull request merged**
