### PR TITLE
Enable multiple editors - Plone 5.2

### PR DESCRIPTION
**Pull request by gotcha**
Depends on https://github.com/plone/plone.app.textfield/pull/45

~~Antoine Duchêne contributor agreement is being prepared.~~ Antoine's contributor agreement is now in.

### CODE REVIEW

**Comment by gotcha** [comment]
@jenkins-plone-org please run jobs

**Comment by gotcha** [comment]
Builds/jobs have been launched with https://github.com/plone/plone.app.textfield/pull/44 (that has been merged.)

@mauritsvanrees Should `plone.app.textfield` be added to https://github.com/plone/buildout.coredev/blob/5.2/checkouts.cfg ?

**Comment by gotcha** [comment]
@mauritsvanrees 

I did relaunch tests.

Now that https://github.com/plone/plone.app.textfield/pull/45 is green, I guess this should be green as well.

**Comment by gotcha** [comment]
This is still in draft as the dependency on a new `plone.app.textfield` release is missing.

**Comment by gotcha** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]

**Comment by mauritsvanrees** [comment]
I have released 3.2.3.

**Pull request merged**
