### PR TITLE
Related Items Widget: In search mode, when no basePath was set, searc…

### PR DESCRIPTION
**Pull request by thet**
…h site-wide.

Fixes: https://github.com/plone/mockup/issues/769

### CODE REVIEW

**Comment by jensens** [comment]
Works now as expected with this change.

**Comment by jensens** [comment]
I don't get why this change has an effect in tests in completely different areas.

**Comment by thet** [comment]
Me neither...

**Comment by thet** [comment]
I hope I fixed it with a ``args['pattern_options'].get('mode', None)`` - pattern_options are likely to be not set.

Running tests again...

**Comment by thet** [comment]
@jensens ready to merge :)

**Pull request merged**
