### PR TITLE
Fieldset labels translatable

### PR DESCRIPTION
**Pull request by ksuess**
Fix https://github.com/plone/plone.app.z3cform/issues/87 for Plone 5.2
Backport of https://github.com/plone/plone.app.z3cform/pull/153

### CODE REVIEW

**Comment by ksuess** [comment]
@jenkins-plone-org please run jobs

**Comment by ksuess** [comment]
@gforcada The check for missing `.pre-commit-config.yaml` fails on branch 3.2.x. Would it make sense to configure also branch 3.2.x with plone.meta or better just ignore the failing check?

**Comment by ksuess** [comment]
Unrelated test failure "Plone Jenkins CI - pull-request-5.2-2.7 ": related items widget

**Comment by gforcada** [comment]
@ksuess yes, the pre-commit check can be ignored, I did restart the jenkins job in case it fixes itself 🤞🏾 

and, I guess, no, there's not much benefit in configuring branches that target only 5.2.

**Comment by ksuess** [comment]
Just for the records: A fake failed jenkins job succeeded with third re-start.

**Comment by ksuess** [comment]
A release of 3.2.x would be nice. Would you, @mauritsvanrees?

**Comment by ksuess** [comment]
Thank you, @mauritsvanrees, for the release!

**Pull request merged**
