### PR TITLE
Fix quoted-printable encoding probs for ajax select widget

### PR DESCRIPTION
**Pull request by thet**
Fix `AjaxSelectWidgetConverter` to decode quoted-printable encoded ascii
strings back to unicode. The Select2 based AjaxSelectWidget returned the ids
which are vocabulary tokens instead of the text. Fixes messed up characters
when selecting tags with non-ASCII characters. Fixes:
plone/Products.CMFPlone#650 - makes obsolete: plone/plone.app.content#34

### CODE REVIEW

**Comment by thet** [comment]
http://jenkins.plone.org/job/pull-request-5.0/591/

**Comment by thet** [comment]
@davisagli @vangheem ^^^

**Comment by davisagli** [comment]
This works for the specific case of the keywords vocabulary in plone.app.vocabularies, but there's no guarantee in general that vocabulary terms will have a token that is made by encoding in this way. To work generally, the converter needs to convert token to value using the vocabulary's getTermByToken

The approach here doesn't solve my use case where I'm trying to use this widget with a different vocabulary.

**Comment by davisagli** [comment]
Btw, I don't expect you to solve my problem for me. I can try to work on it and make an alternate PR later in the week.

**Comment by thet** [comment]
:collision:
but makes sense, what you suggest.

i always avoided to get into the concept of vocabularies, because i always thought simple lists or dictionaries would be all we need.  :hammer:

**Comment by thet** [comment]
this should be done right, of course. if you can contribute to this fix, that would be awesome!

**Comment by davisagli** [comment]
Heh, and I always liked how vocabularies made it possible to have the backend value, token sent in form submission, and title presented to the user all be separate things.

I actually think that the default sequence widget converter in z3c.form may do what we need if we set up the AjaxSelectWidget as a proper sequence widget with a terms attribute. I'll give it a shot later.

**Comment by petschki** [comment]
Just wondering.  Is this related https://github.com/plone/plone.app.widgets/issues/120 ?

**Comment by davisagli** [comment]
Not sure if that's exactly the same, but thanks for bringing it up.

**Comment by jensens** [comment]
confusing, also with the different PRs, whats the status here?

**Comment by jensens** [comment]
I dont think this is still an issue. Please reopen if I am wrong.

**Pull request closed without merging**
