### PR TITLE
fixes plone/Products.CMFPlone#2885

### PR DESCRIPTION
**Pull request by jensens**
see plone/Products.CMFPlone#2885

### CODE REVIEW

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
Jenkins [fails](https://jenkins.plone.org/job/pull-request-5.2-3.6/312/testReport/junit/plone.app.z3cform.tests.test_widgets/AjaxSelectWidgetTests/test_data_converter_collection_with_vocabulary/):

```
'NoneType' object is not callable

  File "/srv/python3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/srv/python3.6/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/jenkins/workspace/pull-request-5.2-3.6/src/plone.app.z3cform/plone/app/z3cform/tests/test_widgets.py", line 1005, in test_data_converter_collection_with_vocabulary
    converter.toFieldValue('token_one;token_two;token_three'),
  File "/home/jenkins/workspace/pull-request-5.2-3.6/src/plone.app.z3cform/plone/app/z3cform/converters.py", line 214, in toFieldValue
    untokenized_value.append(valueType(term.value))
```

Apparantly `valueType` can be None. Probabl solution: do not call `valueType` when it is None. Or maybe check `callable(valuetype)`.

**Comment by mauritsvanrees** [comment]
Also, I initialized towncrier yesterday evening, so the changelog entry should be moved to something like `news/2885.bugfix`. Or `news/105.bugfix` using the current PR number. Does not really matter, as long as the number is unique.

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Comment by jensens** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
