### PR TITLE
Enable multiple editors - Plone 6 (master)

### PR DESCRIPTION
**Pull request by gotcha**
Depends on https://github.com/plone/plone.app.textfield/pull/45

~~Antoine Duchêne contributor agreement is being prepared.~~ Antoine's contributor agreement is now in.

### CODE REVIEW

**Comment by gotcha** [comment]
@jenkins-plone-org please run jobs

**Comment by gotcha** [comment]
@mauritsvanrees @jensens What is the process when a fix in a package depends on a fix in another package ?

Question because this fix depends on a fix to `plone.app.textfield`.

**Comment by mauritsvanrees** [comment]
- Go to jenkins.plone.org and log in.
- Go to a PR job and choose 'Build with parameters', for example for Py 3.7: https://jenkins.plone.org/job/pull-request-6.0-3.7/build?delay=0sec
- Paste the links to both PRs in the textarea and click Build.
- Repeat for the other Python versions.

**Comment by gotcha** [comment]
@mauritsvanrees Thanks for the instructions.

Builds/jobs have been launched.

**Review by mauritsvanrees — APPROVED** [review]
LGTM.

One test failure, but it is an unrelated one so can be ignored.

The PR is marked as draft. Is anything missing?

**Comment by gotcha** [comment]
@mauritsvanrees Nothing is missing except merging https://github.com/plone/plone.app.textfield/pull/45

**Comment by gotcha** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
I have released 4.0.0a4.

**Comment by gotcha** [comment]
Thanks @mauritsvanrees

**Pull request merged**
