### PR TITLE
fix ajax selection in add forms with groups

### PR DESCRIPTION
**Pull request by tomgross**

### CODE REVIEW

**Comment by jensens** [comment]
one failure left, looks like jenkins does not report back plone/jenkins.plone.org#140

**Comment by tomgross** [comment]
What's the state of this?

**Comment by jensens** [comment]
Jenkins reports back again; I started the PR testing. 
You can do this yourself: log in at https://jenkins.plone.org with your github account then go to http://jenkins.plone.org/job/pull-request-5.0/build?delay=0sec and fill in the URL of the PR (like https://github.com/plone/plone.app.z3cform/pull/36) and click on build. The job appears as a check below and shows its state.

**Comment by tomgross** [comment]
http://jenkins.plone.org/job/pull-request-5.0/778/

**Comment by gforcada** [comment]
@tomgross so there seems to be a single error, care to fix it?

**Comment by tomgross** [comment]
Superseeded by https://github.com/plone/plone.app.z3cform/pull/39

**Pull request closed without merging**
