### PR TITLE
Cleanup, housekeeping and deprecations

### PR DESCRIPTION
**Pull request by jensens**
- Deprecated "plone.app.z3cform.object" and moved to
  "plone.app.z3cform.objectsubform" in order to avoid built in names
  as module names, which may result in difficult to debug errors.

- Made existing soft deprecation (by comment) of plone.app.z3cform.layout
  explicit by deprecating using zope.deferredimport.

- removed plone.app.z3cform.queryselect since this was deprecated already
  and removal planned (!) already for Plone 4.1

- Cleanup: pep8, uth8-headers, zca-decorators, ...

### CODE REVIEW

**Comment by gforcada** [comment]
And jenkins job: http://jenkins.plone.org/view/Pkgs/job/package-plone.app.z3cform/

**Comment by jensens** [comment]
@gforcada I dont think code-complexity is something thats good to fix in a cleanup, because this would mean greater refactoring of code, which may reduce the stability or introduce new bugs. It is more a thing to consider writing new code. All other problems are solved, tests are green.

**Comment by hvelarde** [comment]
I totally agree with @jensens

**Comment by thet** [comment]
Only thing is, that the complexity check will complain with every other commit on this package, right @gforcada ?
Otherwise, I agree. Merging....

**Comment by gforcada** [comment]
@jensens @thet more than purit (i.e no errors at all) I like to keep these errors showing up so one is reminded about them. If we do not report this error, then we will forget to try to keep things simpler and less coupled.

And to be honest, Zope and Plone is complex enough that actually adding anything that would raise that error would be IMHO a blocker to get it merged :-)

The idea of this code analysis comments is more to keep things in tone rather than being totally strict.

I specially do not fix the complexity nor the hasattr errors when doing cleanups as fixing those two could easily lead to test errors.

First let's get code that is acceptably clean and after that we can think of being stricter on it.

**Pull request merged**
