### PR TITLE
Config with default template

### PR DESCRIPTION
**Pull request by gforcada**

### CODE REVIEW

**Comment by gforcada** [comment]
@jenkins-plone-org please run jobs

**Review by jensens — APPROVED** [review]

**Review by mauritsvanrees — APPROVED** [review]
LGTM.

But there are three failing tests in all four PR jobs.
Initial guess: the `zpretty` changes break something, but it is easy to blindly point there because that is the biggest change.

**Comment by mauritsvanrees** [comment]
> LGTM.
> 
> But there are three failing tests in all four PR jobs. Initial guess: the `zpretty` changes break something, but it is easy to blindly point there because that is the biggest change.

Indeed `zpretty` is responsible for two of the three test failures.
@ale-rt 

For example a template had this:

```
title="" lang="" disabled="" readonly=""
```

`zpretty` turned it into this:

```
disabled
lang=""
readonly
title=""
```

And this gives errors.  These tests failed:

```
$ bin/test -s plone.app.contenttypes -m test_behaviors_collection
...
Failure in test test_collection_in_edit_form (plone.app.contenttypes.tests.test_behaviors_collection.CollectionBehaviorFunctionalTest.test_collection_in_edit_form)
Traceback (most recent call last):
  File "/Users/maurits/.pyenv/versions/3.11.1/lib/python3.11/unittest/case.py", line 57, in testPartExecutor
    yield
  File "/Users/maurits/.pyenv/versions/3.11.1/lib/python3.11/unittest/case.py", line 623, in run
    self._callTestMethod(testMethod)
  File "/Users/maurits/.pyenv/versions/3.11.1/lib/python3.11/unittest/case.py", line 579, in _callTestMethod
    if method() is not None:
  File "/Users/maurits/shared-eggs/cp311/plone.app.contenttypes-3.0.1-py3.11.egg/plone/app/contenttypes/tests/test_behaviors_collection.py", line 103, in test_collection_in_edit_form
    self.assertEqual(from_control.value, [])
  File "/Users/maurits/.pyenv/versions/3.11.1/lib/python3.11/unittest/case.py", line 873, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Users/maurits/.pyenv/versions/3.11.1/lib/python3.11/unittest/case.py", line 1079, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/Users/maurits/.pyenv/versions/3.11.1/lib/python3.11/unittest/case.py", line 1061, in assertSequenceEqual
    self.fail(msg)
  File "/Users/maurits/.pyenv/versions/3.11.1/lib/python3.11/unittest/case.py", line 703, in fail
    raise self.failureException(msg)
AssertionError: Lists differ: ['CreationDate'] != []

First list contains 1 additional elements.
First extra element 0:
'CreationDate'

- ['CreationDate']
+ []

$ bin/test -s plone.app.relationfield -t schemaeditor.txt
...
File "/Users/maurits/shared-eggs/cp311/plone.app.relationfield-3.0.1-py3.11.egg/plone/app/relationfield/tests/../schemaeditor.txt", line 64, in schemaeditor.txt
Failed example:
    browser.getControl(name='form.widgets.portal_type:list').value
Expected:
    ['Event', 'Folder']
Got:
    ['Event']
----------------------------------------------------------------------
File "/Users/maurits/shared-eggs/cp311/plone.app.relationfield-3.0.1-py3.11.egg/plone/app/relationfield/tests/../schemaeditor.txt", line 97, in schemaeditor.txt
Failed example:
    sorted(my_field.source.query.get('portal_type'))
Expected:
    ['Event', 'Folder']
Got:
    ['Event']
----------------------------------------------------------------------
File "/Users/maurits/shared-eggs/cp311/plone.app.relationfield-3.0.1-py3.11.egg/plone/app/relationfield/tests/../schemaeditor.txt", line 145, in schemaeditor.txt
Failed example:
    browser.getControl(name='form.widgets.portal_type:list').value
Expected:
    ['Event', 'Folder']
Got:
    ['Event']
----------------------------------------------------------------------
File "/Users/maurits/shared-eggs/cp311/plone.app.relationfield-3.0.1-py3.11.egg/plone/app/relationfield/tests/../schemaeditor.txt", line 178, in schemaeditor.txt
Failed example:
    sorted(my_field.value_type.source.query.get('portal_type'))
Expected:
    ['Event', 'Folder']
Got:
    ['Event']
```

Fixed with commit bbca02271808d4528576af58156d21543e148954.
I simply removed the empty attributes, because they were replaced by `tal` anyway.

Same for `multiple` and `checked`, and maybe others.

There is one other test failure.  Technically `zpretty` introduced this one as well, but here it is simply a slightly different attribute output order, and a test in `plone.restapi` was too strict.  Fixed here to work with the old and new code:
https://github.com/plone/plone.restapi/pull/1603

**Comment by mauritsvanrees** [comment]
That worked. :-)
Now Jenkins:

@jenkins-plone-org please run jobs

**Comment by petschki** [comment]
Just got the same issue in an addon. I've created an issue: https://github.com/malthe/chameleon/issues/429

**Pull request merged**
